import { join } from 'path';
import { picrConfig } from '../config/picrConfig.js';
import type { FileFields } from '../db/picrDb.js';
import { thumbnailSizes } from '@shared/thumbnailSize.js';
import {
  legacyVideoMontagePathForParts,
  videoPosterPathForParts,
  videoScrubPathForParts,
} from './videoThumbnailPaths.js';

export interface ThumbnailVariant {
  /** Absolute path to the cache entry. */
  path: string;
  /** Most variants are files; legacy pre-v2 video montage variants are directories. */
  isDirectory: boolean;
}

/**
 * Every cache entry that *could* exist for a file at the given
 * (`relativePath`, `name`, `hash`). Callers treat absent entries as no-ops —
 * many variants are legitimately absent (legacy AVIF files may never have been
 * generated, the decoded intermediate only exists for RAW/PSD/HEIC, thumbnails
 * are lazy so not every size exists). Mirrors the paths built
 * by `thumbnailPath.ts` and `decodedImagePath.ts`, but keyed off primitives so
 * both the runtime (a `dbFile` row) and the migration (a DB record) can use it.
 *
 * The variant order is deterministic, so two calls that differ only in
 * `relativePath`/`name` line up positionally (used by `moveThumbnailFile`).
 */
export const thumbnailVariantPaths = (
  relativePath: string,
  name: string,
  hash: string,
  type: FileFields['type'],
): ThumbnailVariant[] => {
  const dir = join(picrConfig.cachePath, 'thumbs', relativePath);
  const variants: ThumbnailVariant[] = [];

  if (type === 'Image') {
    // Include legacy AVIF thumbnails so rename/delete cleanup can still find
    // files generated by older versions. New thumbnails are JPEG-only.
    for (const size of thumbnailSizes) {
      variants.push({
        path: join(dir, `${name}-${size}-${hash}.jpg`),
        isDirectory: false,
      });
      variants.push({
        path: join(dir, `${name}-${size}-${hash}.avif`),
        isDirectory: false,
      });
    }
    // Decoded intermediate for RAW/PSD/HEIC (absent for sharp-native formats).
    variants.push({
      path: join(dir, `${name}-decoded-${hash}.jpg`),
      isDirectory: false,
    });
  } else if (type === 'Video') {
    for (const size of thumbnailSizes) {
      variants.push({
        path: videoPosterPathForParts(relativePath, name, hash, size, '.jpg'),
        isDirectory: false,
      });
      variants.push({
        path: videoPosterPathForParts(relativePath, name, hash, size, '.avif'),
        isDirectory: false,
      });
    }
    variants.push({
      path: videoScrubPathForParts(relativePath, name, hash),
      isDirectory: false,
    });
    // Transitional cleanup for pre-v2 montage directories. New video variants
    // are versioned files.
    variants.push({
      path: legacyVideoMontagePathForParts(relativePath, name, hash, 'md'),
      isDirectory: true,
    });
  }
  // FileType.File has no thumbnails.

  return variants;
};
