version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: quarterly
      time: '05:00'
      timezone: America/New_York
    open-pull-requests-limit: 1
    labels:
      - dependencies
      - github-actions
    groups:
      github-actions:
        patterns:
          - '*'

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: monthly
      time: '05:15'
      timezone: America/New_York
    open-pull-requests-limit: 1
    cooldown:
      semver-minor-days: 21
      semver-patch-days: 7
    ignore:
      - dependency-name: '*'
        update-types:
          - version-update:semver-major
    labels:
      - dependencies
      - npm
    groups:
      npm-root:
        patterns:
          - '*'

  - package-ecosystem: npm
    directory: /backend
    schedule:
      interval: monthly
      time: '05:30'
      timezone: America/New_York
    open-pull-requests-limit: 1
    cooldown:
      semver-minor-days: 21
      semver-patch-days: 7
    ignore:
      - dependency-name: '*'
        update-types:
          - version-update:semver-major
    labels:
      - dependencies
      - npm
    groups:
      npm-backend:
        patterns:
          - '*'

  - package-ecosystem: npm
    directory: /frontend
    schedule:
      interval: monthly
      time: '05:45'
      timezone: America/New_York
    open-pull-requests-limit: 1
    cooldown:
      semver-minor-days: 21
      semver-patch-days: 7
      exclude:
        - '@picr/react-grid-gallery'
    ignore:
      - dependency-name: '*'
        update-types:
          - version-update:semver-major
    labels:
      - dependencies
      - npm
    groups:
      npm-frontend:
        patterns:
          - '*'

  - package-ecosystem: npm
    directory: /app
    schedule:
      interval: monthly
      time: '06:00'
      timezone: America/New_York
    open-pull-requests-limit: 0
    labels:
      - dependencies
      - npm
    groups:
      npm-app-security:
        applies-to: security-updates
        patterns:
          - '*'

  - package-ecosystem: npm
    directory: /shared
    schedule:
      interval: monthly
      time: '06:15'
      timezone: America/New_York
    open-pull-requests-limit: 1
    cooldown:
      semver-minor-days: 21
      semver-patch-days: 7
    ignore:
      - dependency-name: '*'
        update-types:
          - version-update:semver-major
    labels:
      - dependencies
      - npm
    groups:
      npm-shared:
        patterns:
          - '*'

  - package-ecosystem: npm
    directory: /ping
    schedule:
      interval: monthly
      time: '06:30'
      timezone: America/New_York
    open-pull-requests-limit: 1
    cooldown:
      semver-minor-days: 21
      semver-patch-days: 7
    ignore:
      - dependency-name: '*'
        update-types:
          - version-update:semver-major
    labels:
      - dependencies
      - npm
    groups:
      npm-ping:
        patterns:
          - '*'
