import type { IPicrConfiguration } from './IPicrConfiguration.js';

export const picrConfig: IPicrConfiguration = {
  baseUrl: '',
  baseUrlOrigin: '',
  baseUrlPathname: '',
  ffmpegPath: undefined,
  ffprobePath: undefined,
  exiftoolPath: undefined,
  magickPath: undefined,
  mediaCaps: {
    raw: false,
    psd: false,
    psb: false,
    heic: false,
  },
  videoAcceleration: 'auto',
  videoAccelerationDevice: '/dev/dri/renderD128',
  videoAccelerationMode: 'cpu',
  videoAccelerationReason: 'Video acceleration not yet detected',
  inodeSupport: 'unknown',
  inodeSupportReason: 'Inode support not yet detected',
  pingToken: undefined,
  cachePath: '',
  mediaPath: '',
  updateMetadata: false,
  fileWatcherMode: 'native',
  onViewScanMode: 'off',
  pollingSeconds: 20,
  scheduledScanHours: 0,
  loginRateLimitEnabled: true,
  loginRateLimitWindowMinutes: 15,
  loginRateLimitIpMaxAttempts: 30,
  loginRateLimitUserIpMaxAttempts: 5,
  loginRateLimitBlockMinutes: 15,
  loginRateLimitMaxBlockMinutes: 60,
};
