services:
  db:
    image: postgres:17
    container_name: picr-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: picr
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U user -d picr']
      interval: 5s
      timeout: 5s
      retries: 12
      start_period: 5s
    ports:
      - '54321:5432'
    volumes:
      - picr-db-data:/var/lib/postgresql/data
volumes:
  picr-db-data:
