



-- Generated by `drizzle-kit generate`
ALTER TYPE "public"."enum_AccessLogs_type" RENAME TO "accesslogs_type";--> statement-breakpoint
ALTER TYPE "public"."enum_Users_commentPermissions" RENAME TO "user_commentPermissions";--> statement-breakpoint
ALTER TYPE "public"."enum_Files_flag" RENAME TO "file_flag";--> statement-breakpoint
ALTER TYPE "public"."enum_Files_type" RENAME TO "file_type";--> statement-breakpoint
ALTER TYPE "public"."enum_Brandings_primaryColor" RENAME TO "theme_color";--> statement-breakpoint
ALTER TYPE "public"."enum_Brandings_mode" RENAME TO "theme_mode";--> statement-breakpoint
ALTER TYPE "public"."enum_Users_userType" RENAME TO "user_type";--> statement-breakpoint

-- Artistan hand crafted Isaac goodness
UPDATE "Files" set "rating" = 0 where "rating" is null;
UPDATE "Files" set "exists" = false where "exists" is null;
UPDATE "Files" set "totalComments" = 0 where "totalComments" is null;
UPDATE "Folders" set "exists" = false where "exists" is null;
UPDATE "Users" set "name" = 'Unnamed User' where "name" is null;
UPDATE "Users" set "enabled" = false where "enabled" is null;
UPDATE "Users" set "commentPermissions" = 'none' where "commentPermissions" is null;
DELETE FROM "Users" where "folderId" IS NULL;
UPDATE "Users" SET "userType" = 'Link' where "userType" is null and "uuid" is not null;
UPDATE "Users" SET "userType" = 'Admin' where "userType" is null and "hashedPassword" is not null;

-- Generated by `drizzle-kit generate`
ALTER TABLE "Files" ALTER COLUMN "name" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "Files" ALTER COLUMN "relativePath" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "Files" ALTER COLUMN "rating" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "Files" ALTER COLUMN "fileSize" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "Files" ALTER COLUMN "fileLastModified" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "Files" ALTER COLUMN "exists" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "Files" ALTER COLUMN "totalComments" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "Files" ALTER COLUMN "folderId" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "Folders" ALTER COLUMN "name" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "Folders" ALTER COLUMN "exists" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "Users" ALTER COLUMN "name" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "Users" ALTER COLUMN "enabled" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "Users" ALTER COLUMN "commentPermissions" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "Users" ALTER COLUMN "folderId" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "Users" ALTER COLUMN "userType" SET NOT NULL;