// Writes an introspection snapshot of the executable GraphQL schema so that
// `npm run gql` can run offline, with no backend server, database, configured
// environment, or open HTTP port. See AGENTS.md "Autogenerated Files".
//
// This must run under backend's own tsconfig and module resolution (see the
// root `gql:schema` script). Importing the schema from a different module
// realm makes graphql-js throw "Cannot use GraphQLSchema from another module
// or realm", because the schema is built against graphql's ESM entry point.
import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { introspectionFromSchema, validateSchema } from 'graphql';
import { schema } from '../graphql/schema.js';

const outputArgument = process.argv[2];
if (!outputArgument) {
  process.stderr.write(
    'Usage: exportGraphqlSchema.ts <output-introspection-json>\n',
  );
  process.exit(1);
}

const errors = validateSchema(schema);
if (errors.length > 0) {
  process.stderr.write(
    `GraphQL schema validation failed:\n${errors
      .map(({ message }) => `- ${message}`)
      .join('\n')}\n`,
  );
  process.exit(1);
}

const outputPath = resolve(outputArgument);
mkdirSync(dirname(outputPath), { recursive: true });
writeFileSync(
  outputPath,
  `${JSON.stringify(
    // `specifiedByUrl: false` is load-bearing: it matches what the previous
    // HTTP introspection produced, keeping `schema.graphql` byte-identical.
    // Setting it to true adds `@specifiedBy(url: ...)` to the JSON scalar.
    introspectionFromSchema(schema, { specifiedByUrl: false }),
    null,
    2,
  )}\n`,
);

// Importing the schema transitively constructs runtime objects (such as the
// Expo client and Ping coordinator). None currently hold the event loop open,
// but exit explicitly so a future stray timer cannot silently hang codegen.
process.exit(0);
