import { ReactNode } from 'react';
import {
  ApertureIcon,
  ArtistIcon,
  AspectRatioIcon,
  AudioIcon,
  BitrateIcon,
  CalendarIcon,
  CameraIcon,
  DateEditedIcon,
  DurationIcon,
  FileIcon,
  FramerateIcon,
  HeightIcon,
  ISOIcon,
  LensIcon,
  RatingStarsIcon,
  ShutterSpeedIcon,
  VideoMetadataIcon,
  WidthIcon,
} from '../../PicrIcons';

export const metadataIcons: Record<string, ReactNode> = {
  __typename: null,
  //PHOTO
  Camera: <CameraIcon />,
  Lens: <LensIcon />,
  ISO: <ISOIcon />,
  ExposureTime: <ShutterSpeedIcon />,
  Aperture: <ApertureIcon />,
  Artist: <ArtistIcon />,
  DateTimeEdit: <DateEditedIcon />,
  DateTimeOriginal: <CalendarIcon />,
  //VIDEO
  Audio: <AudioIcon />,
  Framerate: <FramerateIcon />,
  Height: <HeightIcon />,
  Width: <WidthIcon />,
  Video: <VideoMetadataIcon />,
  Format: <FileIcon />,
  Duration: <DurationIcon />,
  Bitrate: <BitrateIcon />,
  AspectRatio: <AspectRatioIcon />,
  Rating: <RatingStarsIcon />,
} as const;
