// This file is autogenerated by: node scripts/generate-fonts.ts
// Do not edit directly. Update shared/branding/fontRegistry.ts instead.
// Target: app

const signika_400 = require('./assets/fonts/signika-400.ttf');
const signika_600 = require('./assets/fonts/signika-600.ttf');
const signika_700 = require('./assets/fonts/signika-700.ttf');
const inter_400 = require('./assets/fonts/inter-400.ttf');
const inter_500 = require('./assets/fonts/inter-500.ttf');
const inter_700 = require('./assets/fonts/inter-700.ttf');
const source_sans_3_400 = require('./assets/fonts/source-sans-3-400.ttf');
const source_sans_3_500 = require('./assets/fonts/source-sans-3-500.ttf');
const source_sans_3_700 = require('./assets/fonts/source-sans-3-700.ttf');
const manrope_400 = require('./assets/fonts/manrope-400.ttf');
const manrope_500 = require('./assets/fonts/manrope-500.ttf');
const manrope_700 = require('./assets/fonts/manrope-700.ttf');
const merriweather_sans_300 = require('./assets/fonts/merriweather-sans-300.ttf');
const merriweather_sans_400 = require('./assets/fonts/merriweather-sans-400.ttf');
const merriweather_sans_700 = require('./assets/fonts/merriweather-sans-700.ttf');
const montserrat_200 = require('./assets/fonts/montserrat-200.ttf');
const montserrat_400 = require('./assets/fonts/montserrat-400.ttf');
const montserrat_700 = require('./assets/fonts/montserrat-700.ttf');
const merriweather_300 = require('./assets/fonts/merriweather-300.ttf');
const merriweather_400 = require('./assets/fonts/merriweather-400.ttf');
const merriweather_700 = require('./assets/fonts/merriweather-700.ttf');
const lora_400 = require('./assets/fonts/lora-400.ttf');
const lora_700 = require('./assets/fonts/lora-700.ttf');
const libre_baskerville_400 = require('./assets/fonts/libre-baskerville-400.ttf');
const libre_baskerville_700 = require('./assets/fonts/libre-baskerville-700.ttf');
const bebas_neue_400 = require('./assets/fonts/bebas-neue-400.ttf');
const abril_fatface_400 = require('./assets/fonts/abril-fatface-400.ttf');
const poiret_one_400 = require('./assets/fonts/poiret-one-400.ttf');
const amatic_sc_400 = require('./assets/fonts/amatic-sc-400.ttf');
const oleo_script_400 = require('./assets/fonts/oleo-script-400.ttf');
const pacifico_400 = require('./assets/fonts/pacifico-400.ttf');
const pinyon_script_400 = require('./assets/fonts/pinyon-script-400.ttf');
const dancing_script_400 = require('./assets/fonts/dancing-script-400.ttf');
const dancing_script_700 = require('./assets/fonts/dancing-script-700.ttf');
const jetbrains_mono_400 = require('./assets/fonts/jetbrains-mono-400.ttf');
const jetbrains_mono_700 = require('./assets/fonts/jetbrains-mono-700.ttf');
const atkinson_hyperlegible_next_400 = require('./assets/fonts/atkinson-hyperlegible-next-400.ttf');
const atkinson_hyperlegible_next_700 = require('./assets/fonts/atkinson-hyperlegible-next-700.ttf');
const atkinson_hyperlegible_mono_400 = require('./assets/fonts/atkinson-hyperlegible-mono-400.ttf');
const atkinson_hyperlegible_mono_700 = require('./assets/fonts/atkinson-hyperlegible-mono-700.ttf');
const roboto_400 = require('./assets/fonts/roboto-400.ttf');
const roboto_500 = require('./assets/fonts/roboto-500.ttf');
const roboto_700 = require('./assets/fonts/roboto-700.ttf');

export const fontFiles = {
  'signika-400': signika_400,
  'signika-600': signika_600,
  'signika-700': signika_700,
  'inter-400': inter_400,
  'inter-500': inter_500,
  'inter-700': inter_700,
  'source-sans-3-400': source_sans_3_400,
  'source-sans-3-500': source_sans_3_500,
  'source-sans-3-700': source_sans_3_700,
  'manrope-400': manrope_400,
  'manrope-500': manrope_500,
  'manrope-700': manrope_700,
  'merriweather-sans-300': merriweather_sans_300,
  'merriweather-sans-400': merriweather_sans_400,
  'merriweather-sans-700': merriweather_sans_700,
  'montserrat-200': montserrat_200,
  'montserrat-400': montserrat_400,
  'montserrat-700': montserrat_700,
  'merriweather-300': merriweather_300,
  'merriweather-400': merriweather_400,
  'merriweather-700': merriweather_700,
  'lora-400': lora_400,
  'lora-700': lora_700,
  'libre-baskerville-400': libre_baskerville_400,
  'libre-baskerville-700': libre_baskerville_700,
  'bebas-neue-400': bebas_neue_400,
  'abril-fatface-400': abril_fatface_400,
  'poiret-one-400': poiret_one_400,
  'amatic-sc-400': amatic_sc_400,
  'oleo-script-400': oleo_script_400,
  'pacifico-400': pacifico_400,
  'pinyon-script-400': pinyon_script_400,
  'dancing-script-400': dancing_script_400,
  'dancing-script-700': dancing_script_700,
  'jetbrains-mono-400': jetbrains_mono_400,
  'jetbrains-mono-700': jetbrains_mono_700,
  'atkinson-hyperlegible-next-400': atkinson_hyperlegible_next_400,
  'atkinson-hyperlegible-next-700': atkinson_hyperlegible_next_700,
  'atkinson-hyperlegible-mono-400': atkinson_hyperlegible_mono_400,
  'atkinson-hyperlegible-mono-700': atkinson_hyperlegible_mono_700,
  'roboto-400': roboto_400,
  'roboto-500': roboto_500,
  'roboto-700': roboto_700,
} as const;

export const fontAssets = {
  'default': 'Signika',
  'signika': 'Signika',
  'inter': 'Inter',
  'source-sans-3': 'Source Sans 3',
  'manrope': 'Manrope',
  'merriweather-sans': 'Merriweather Sans',
  'montserrat': 'Montserrat',
  'merriweather': 'Merriweather',
  'lora': 'Lora',
  'libre-baskerville': 'Libre Baskerville',
  'bebas-neue': 'Bebas Neue',
  'abril-fatface': 'Abril Fatface',
  'poiret-one': 'Poiret One',
  'amatic-sc': 'Amatic SC',
  'oleo-script': 'Oleo Script',
  'pacifico': 'Pacifico',
  'pinyon-script': 'Pinyon Script',
  'dancing-script': 'Dancing Script',
  'jetbrains-mono': 'JetBrains Mono',
  'atkinson-hyperlegible-next': 'Atkinson Hyperlegible Next',
  'atkinson-hyperlegible-mono': 'Atkinson Hyperlegible Mono',
} as const;

export const fontWeightsByKey = {
  "default": [
    400,
    600,
    700
  ],
  "signika": [
    400,
    600,
    700
  ],
  "inter": [
    400,
    500,
    700
  ],
  "source-sans-3": [
    400,
    500,
    700
  ],
  "manrope": [
    400,
    500,
    700
  ],
  "merriweather-sans": [
    300,
    400,
    700
  ],
  "montserrat": [
    200,
    400,
    700
  ],
  "merriweather": [
    300,
    400,
    700
  ],
  "lora": [
    400,
    700
  ],
  "libre-baskerville": [
    400,
    700
  ],
  "bebas-neue": [
    400
  ],
  "abril-fatface": [
    400
  ],
  "poiret-one": [
    400
  ],
  "amatic-sc": [
    400
  ],
  "oleo-script": [
    400
  ],
  "pacifico": [
    400
  ],
  "pinyon-script": [
    400
  ],
  "dancing-script": [
    400,
    700
  ],
  "jetbrains-mono": [
    400,
    700
  ],
  "atkinson-hyperlegible-next": [
    400,
    700
  ],
  "atkinson-hyperlegible-mono": [
    400,
    700
  ]
} as const;
