// This file is autogenerated by: node scripts/generate-fonts.ts
// Do not edit directly. Update shared/branding/fontRegistry.ts instead.
// Target: frontend

import '@fontsource/signika/400.css';
import '@fontsource/signika/600.css';
import '@fontsource/signika/700.css';
import '@fontsource/inter/400.css';
import '@fontsource/inter/500.css';
import '@fontsource/inter/700.css';
import '@fontsource/source-sans-3/400.css';
import '@fontsource/source-sans-3/500.css';
import '@fontsource/source-sans-3/700.css';
import '@fontsource/manrope/400.css';
import '@fontsource/manrope/500.css';
import '@fontsource/manrope/700.css';
import '@fontsource/merriweather-sans/300.css';
import '@fontsource/merriweather-sans/400.css';
import '@fontsource/merriweather-sans/700.css';
import '@fontsource/montserrat/200.css';
import '@fontsource/montserrat/400.css';
import '@fontsource/montserrat/700.css';
import '@fontsource/merriweather/300.css';
import '@fontsource/merriweather/400.css';
import '@fontsource/merriweather/700.css';
import '@fontsource/lora/400.css';
import '@fontsource/lora/700.css';
import '@fontsource/libre-baskerville/400.css';
import '@fontsource/libre-baskerville/700.css';
import '@fontsource/bebas-neue/400.css';
import '@fontsource/abril-fatface/400.css';
import '@fontsource/poiret-one/400.css';
import '@fontsource/amatic-sc/400.css';
import '@fontsource/oleo-script/400.css';
import '@fontsource/pacifico/400.css';
import '@fontsource/pinyon-script/400.css';
import '@fontsource/dancing-script/400.css';
import '@fontsource/dancing-script/700.css';
import '@fontsource/jetbrains-mono/400.css';
import '@fontsource/jetbrains-mono/700.css';
import '@fontsource/atkinson-hyperlegible-next/400.css';
import '@fontsource/atkinson-hyperlegible-next/700.css';
import '@fontsource/atkinson-hyperlegible-mono/400.css';
import '@fontsource/atkinson-hyperlegible-mono/700.css';
import '@fontsource/roboto/400.css';
import '@fontsource/roboto/500.css';
import '@fontsource/roboto/700.css';

export const fontFamilies = {
  default: 'Signika',
  signika: 'Signika',
  inter: 'Inter',
  'source-sans-3': 'Source Sans 3',
  manrope: 'Manrope',
  'merriweather-sans': 'Merriweather Sans',
  montserrat: 'Montserrat',
  merriweather: 'Merriweather',
  lora: 'Lora',
  'libre-baskerville': 'Libre Baskerville',
  'bebas-neue': 'Bebas Neue',
  'abril-fatface': 'Abril Fatface',
  'poiret-one': 'Poiret One',
  'amatic-sc': 'Amatic SC',
  'oleo-script': 'Oleo Script',
  pacifico: 'Pacifico',
  'pinyon-script': 'Pinyon Script',
  'dancing-script': 'Dancing Script',
  'jetbrains-mono': 'JetBrains Mono',
  'atkinson-hyperlegible-next': 'Atkinson Hyperlegible Next',
  'atkinson-hyperlegible-mono': 'Atkinson Hyperlegible Mono',
} as const;
