name: PICR Docker Build and Push (manual)

on:
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build.yml
  vars:
    runs-on: ubuntu-24.04
    outputs:
      short_sha: ${{ steps.vars.outputs.short_sha }}
    steps:
      - name: Compute short SHA
        id: vars
        run: echo "short_sha=${GITHUB_SHA::7}" >> "$GITHUB_OUTPUT"
  docker_publish:
    needs: [build, vars]
    uses: ./.github/workflows/docker-publish.yml
    with:
      build_channel: development
      development_build_sha: ${{ needs.vars.outputs.short_sha }}
      image_tags: isaacinsoll/picr:commit-${{ needs.vars.outputs.short_sha }}
      version: ${{ github.ref_name }}
    secrets: inherit
