name: PICR on push

on:
  push:
    paths-ignore:
      - 'lightroom/**'
      - 'docs/**'
      - '*.md'
  pull_request:
    paths-ignore:
      - 'lightroom/**'
      - 'docs/**'
      - '*.md'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    uses: ./.github/workflows/build.yml
