name: PICR Docker Build and Push

# failed on pushing to ghcr.io
# presumably just do this https://github.com/docker/login-action#github-container-registry
# I didn't bother as we just use docker hub :)
on:
  release:
    types: [published]

jobs:
  build:
    # Skip for Lightroom plugin releases
    if: ${{ !startsWith(github.ref_name, 'lightroom-') }}
    uses: ./.github/workflows/build.yml
  docker_publish:
    needs: build
    uses: ./.github/workflows/docker-publish.yml
    with:
      build_channel: release
      image_tags: |
        isaacinsoll/picr:${{ github.ref_name }}
        isaacinsoll/picr:latest
      version: ${{ github.ref_name }}
    secrets: inherit
